# Generated by Django 3.0.5 on 2020-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('eventType', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('eventDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
