# Generated by Django 3.0.5 on 2020-04-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventsToBaby',
            field=models.ManyToManyField(to='babies.Babie'),
        ),
    ]
