# Generated by Django 3.0.5 on 2020-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_eventstobaby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventsToBaby',
        ),
    ]
